### PR TITLE
CMDEV-26 play with file-related path

### PR DESCRIPTION
**Pull request by msfuko**
* try on file to s3 route
* try on choise & when context in Camel - could decide message should go with which route

### CODE REVIEW

**Comment by msfuko** [comment]
Hi @hidetosaito ,

This is the sample for s3 route which I tried yesterday.
Just simply commit and hope if we could get some thought to compare with other choices.

Regards,
Chloe

**Comment by msfuko** [comment]
How-to try s3 route:

* modify fileDirectory and fileEndpoint in spring-camel-config.xml
  Please modify to your local test folder path
* modify producerS3Endpoint in spring-camel-config.xml
  The value is set to s3://chloe-test now. Modify it if you would like to change the destination.
* visit http://localhost:8080/spring-camel-sample/rest/message/s3 and you might see happy-file-test.txt in your s3 destination

The basic idea is that if you send a FileMessage rather than ContentMessage, Camel will route you to S3 instead of SQS.

**Comment by hidetosaito** [comment]
Hi @msfuko 

Thanks for an additional sample.
i could understand much easier for concept of Camel. Your code works very well!

i just play with Eclipse debugger to trace the code, but i encounter the difficulty that i can't trace after MessageGatewayImpl.send()

debug

so i'm a little bit worry about when we encounter any issue, how can we trace the code. Although i like the concept of Camel's RouteBuilder (DSL), but i think MessageRouter is one of important logic, if can't debug with jdb, it might impact for developer.

Do you have any ideas how can we debug Apache Camel ? or do you think is this a trade off if we use this Framework?

please advice!

**Comment by msfuko** [comment]
Hi @hidetosaito ,

Sorry for the delay, this is noted. I also took a look on debug mode. I'm able to see further steps, however, I'm unable to see the exchange route inside. 
I think [Camel debugger](http://camel.apache.org/debugger.html) might be a way to solve it which seems like need to add some codes for tracing. 
Will take a look and also enhance Camel code once I got back from jms-sqs.

Thanks for the understanding.


Regards,
Chloe

**Comment by hidetosaito** [comment]
Hi @msfuko 

good finding. if we can debug exchange route inside, i don't have any concern to use Camel. Also in reality, most of developer tends to write logger.debug() or System.out.println() for the debugging purpose, please also consider whether this Framework is good for developer or not.

overall, i think now we are getting used to implement message queue client, i'm ok either Camel or Spring Framework or Spring Integration.

let's focus on to judge whether JMS-SQS or JMS-SQS+patch or JMS + other JMS server first.

**Pull request merged**
