### PR TITLE
CMDEV-26 add consumer code...

### PR DESCRIPTION
**Pull request by msfuko**
Hi @hidetosaito ,

I'd like to list some updates, problem I encountered and concerns as below.

- add reply consumer route, the message could work like JMS DAO that you did.
- still cannot make response receiver gets corresponding message. the reasons are -
   * Camel is also using [JMSReplyTo](http://camel.apache.org/request-reply.html) to specify the destination by Exchange InOut message. so it won't work if we use its build-in InOut.
   * If we do on our own by filter - 
     response receiver still could not get the corresponding message rule although we could hide the correlationId attribute in the message. the reason is that route engine go its own way. The direction of the response route would be as below:
image
The response listener listens response queue until at least one message is inside. When it's triggered, however, the destination of the route would go to one bean or processor which did not know which original request we're waiting for...
Please refer to ProducerRouteBuilder shown as below 
```
		from(replyQueueEndpoint)
		.routeId("recv-response-sqs")
		.log(LoggingLevel.INFO, "[Content] receive responce")
		.errorHandler(deadLetterChannel("log:ProducerfailedLetter"))
		//.process(new SampleResponseProcess())   
		//.filter("${body.getCorrelationId} == true")   //--> who I should filter??
		.transform().method("messageTransformer", "transform")
		.log(LoggingLevel.INFO, "[Content] going to processing received message")
		.bean(SampleService.class, "receiveMessage");
```
filter could not work because we don't know who we're waiting for when the builder initiates and runs.
- Even if we achieve it by our own - the performance won't be good in this model.
I just think about the statement in [Camel SQS](http://camel.apache.org/aws-sqs.html)
image
It uses SQS visibility timeout to lock the queue from other receivers. 
It means if I have 1000 messages and my visibility timeout is 300s. Then the worst case I have to wait up to 300 * 999 secs to get my response. Of course we could set visibility timeout as 0s, but it will make lots of workers doing the same thing and it's an important feature in SQS to make our service reliable. Even if we set it as 0, it won't be able to scale out gracefully.

- I'm wondering whether request-reply pattern good for our design and SQS. It seems like SQS could always get benefits in below architecture.
image
But I'm not quite sure whether we could get any benefits from JMS and Camel if we want to scale out.
Is it possible that [asynchronous http client](http://stackoverflow.com/questions/3142915/how-do-you-create-an-asynchronous-http-request-in-java) is better for our needs? :-S e.g. [async-http-client](https://github.com/AsyncHttpClient/async-http-client) 
It looks like could get better performance based on our arch..

If we're going to do more micro services next - I still don't feel fully comfortable with request-reply queue model :'-(
Sorry that taking so long time to figure it out for all of this...

Regards,
Chloe

### CODE REVIEW

**Comment by hidetosaito** [comment]
Hi @msfuko 

thanks update. according to your research result of Camel and SQS, i'm agree those combination is not suitable for request-reply pattern.

let me explain our original scope, because i don't want you to loose the point.

## problem
i had a concern if we deploy new-cm, JIRA will became busy and bottle neck if many user access and/or many instances has deployed as below.

current

because frontend to JIRA are synchronized 

synchronized

:exclamation: also concern when JIRA is maintenance (ex: upgrade, rebooting), user might lost RFC submission, in another word, we *can't maintain* JIRA easily after we launch new-cm.


## solution 1
my idea was use queue (regardless SQS or other queue server) as below

goal

with this solution, we could support

- number of user access growth
- number of backend api call growth
- JIRA maintenance

because we can control backend(consumer) <--> JIRA

as your research result, we believe we can't use SQS, but i still believe we could use JMS compliant queue server, such as ActiveMQ to achieve this


## solution 2
Your suggestion is ; use thread pool (and internal queue) inside of backend something like below

thread_pool

with this solution, we could support

- number of user access growth

but can't support

- number of backend api call growth
- JIRA maintenance

because if we deploy many backend, JIRA will became busy too.

By the way, this design, i remember we just use @Async annotation in SpringFramework is easier.
http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#scheduling-annotation-support-async 


## solution 3
if request-reply pattern (solution 1) is complicated, we may mix those of them.

for example

- use SQS for one-way message (void method; ex: issue JIRA ticket)
- use thread-pool (@Async) for API call (with return value method; ex: get JIRA ticket list)

compromized

with this solution, we could support

- number of user access growth
- number of backend api call growth (for one-way message only)
- JIRA maintenance (for one-way message only)

but can't support

- number of backend api call growth (for API call with return value)
- JIRA maintenance (for API call with return value)

perhaps we can mitigate if we use retry and timeout mechanism for "API call with return value" part, but not 100% sure whether this design is more complicated than solution 1 or not.


please give your opinion. i'm fine if we deploy and maintain ActiveMQ server by ourself.

**Comment by msfuko** [comment]
Hi @hidetosaito ,

Thanks for your time and patience for the discussion :-)
Below is the conclusion -

* Architecture
image

* When the request goes to server, server will follow below flow by read or write requests
- Read
image

- Write
image

* Enqueue/Dequeue might use JMS-SQS 

* Will investigate framework for cache - Spring framework should support [some annotation](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/cache/annotation/EnableCaching.html)

* Check out ElaticCache first

* Might need to implement plugin to listen JIRA ticket update from JIRA directly.

Thank you very much.

**Comment by hidetosaito** [comment]
Hi @msfuko 

Very good!

Only one thing for Architecture diagram, server should have a link to JIRA directly right? in case "Exist in Cache?" returns false.

For the Cache part, please remind that 

1 i prefer the DAO logic code that transparent to access to the cache, like an annotation way. in another word, don't wish to write some cache manipulation code something like below

```python
function get_foo(foo_id)
    foo = memcached_get("foo:" . foo_id)
    return foo if defined foo

    foo = fetch_foo_from_database(foo_id)
    memcached_set("foo:" . foo_id, foo)
    return foo
end
```

2 however, annotation way might cause difficulty to trace the code (ex: break point while debug), so it would better to have the way whether cache hit or miss at least in the debug log

3 if you unclear for the usage of cache or annotation or framework or AWS service, just try to implement low level (like 1. example, manipulate cache directly) to understand basic mechanism first. please don't spend too much for "how to setup/use framework/ElaticCache"

**Comment by msfuko** [comment]
Hi @hidetosaito,

For the second item - ehcache has debug log. I'm thinking elasticcache should have also if we set our logging level is debug. 
Let me get back to you once I have complete information.

Regards,
Chloe

**Pull request merged**
